# Generated by Django 2.2 on 2019-04-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='songs',
            field=models.IntegerField(default=0),
        ),
    ]
