# Generated by Django 2.2 on 2019-04-15 17:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_album_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='year',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
